# Reputation System

# Reputation Points
OUTLAW_GAIN = 5
OUTLAW_LOSS = 3
MARSHAL_GAIN = 3
MARSHAL_LOSS = 5
BOUNTY_HUNTER_GAIN = 5
BOUNTY_HUNTER_GAIN_2 = 10
BOUNTY_HUNTER_GAIN_3 = 25
BOUNTY_HUNTER_LOSS = 3
MOST_WANTED_GAIN = 5
MOST_WANTED_GAIN_2 = 10
MOST_WANTED_GAIN_3 = 25
MOST_WANTED_LOSS = 3

# Prestige Thresholds
OUTLAW_PRESTIGE_1 = 500
OUTLAW_PRESTIGE_2 = 2000
OUTLAW_PRESTIGE_3 = 5000
NOTORIOUS_OUTLAW = 10000
MARSHAL_PRESTIGE_1 = 500
MARSHAL_PRESTIGE_2 = 2000
MARSHAL_PRESTIGE_3 = 5000
BIG_IRON_MARSHAL = 10000
BOUNTY_HUNTER_PRESTIGE_1 = 500
BOUNTY_HUNTER_PRESTIGE_2 = 2000
BOUNTY_HUNTER_PRESTIGE_3 = 5000
NIGHTMARE_BOUNTY_HUNTER = 10000
MOST_WANTED_LEVEL_1 = 500
MOST_WANTED_LEVEL_2 = 2000
MOST_WANTED_LEVEL_3 = 5000
DEMON_MOST_WANTED = 10000

# Badge Titles
OUTLAW_PRESTIGE_1_BADGE = "REBEL"
OUTLAW_PRESTIGE_2_BADGE = "BANDIT"
OUTLAW_PRESTIGE_3_BADGE = "LAWLESS"
NOTORIOUS_OUTLAW_PRESTIGE_BADGE = "NOTORIOUS"
MARSHAL_PRESTIGE_1_BADGE = "DEPUTY"
MARSHAL_PRESTIGE_2_BADGE = "PEACEKEEPER"
MARSHAL_PRESTIGE_3_BADGE = "REVERED"
BIG_IRON_MARSHAL_PRESTIGE_BADGE = "BIG IRON"
BOUNTY_HUNTER_PRESTIGE_1_BADGE = "CHECK CHASER"
BOUNTY_HUNTER_PRESTIGE_2_BADGE = "TROPHY TRACKER"
BOUNTY_HUNTER_PRESTIGE_3_BADGE = "BLOODHOUND"
NIGHTMARE_BOUNTY_HUNTER_PRESTIGE_BADGE = "NIGHTMARE"
MOST_WANTED_LEVEL_1_BADGE = "ON THE RUN"
MOST_WANTED_LEVEL_2_BADGE = "HIGH ROLLER"
MOST_WANTED_LEVEL_3_BADGE = "TOP DOG"
DEMON_MOST_WANTED_PRESTIGE_BADGE = "DEMON"

# Reputation Evaluation Logic
def get_player_title(reputation_type: str, score: int) -> str:
    if reputation_type == "outlaw":
        if score >= NOTORIOUS_OUTLAW:
            return NOTORIOUS_OUTLAW_PRESTIGE_BADGE
        elif score >= OUTLAW_PRESTIGE_3:
            return OUTLAW_PRESTIGE_3_BADGE
        elif score >= OUTLAW_PRESTIGE_2:
            return OUTLAW_PRESTIGE_2_BADGE
        elif score >= OUTLAW_PRESTIGE_1:
            return OUTLAW_PRESTIGE_1_BADGE
    elif reputation_type == "marshal":
        if score >= BIG_IRON_MARSHAL:
            return BIG_IRON_MARSHAL_PRESTIGE_BADGE
        elif score >= MARSHAL_PRESTIGE_3:
            return MARSHAL_PRESTIGE_3_BADGE
        elif score >= MARSHAL_PRESTIGE_2:
            return MARSHAL_PRESTIGE_2_BADGE
        elif score >= MARSHAL_PRESTIGE_1:
            return MARSHAL_PRESTIGE_1_BADGE
    elif reputation_type == "bounty_hunter":
        if score >= NIGHTMARE_BOUNTY_HUNTER:
            return NIGHTMARE_BOUNTY_HUNTER_PRESTIGE_BADGE
        elif score >= BOUNTY_HUNTER_PRESTIGE_3:
            return BOUNTY_HUNTER_PRESTIGE_3_BADGE
        elif score >= BOUNTY_HUNTER_PRESTIGE_2:
            return BOUNTY_HUNTER_PRESTIGE_2_BADGE
        elif score >= BOUNTY_HUNTER_PRESTIGE_1:
            return BOUNTY_HUNTER_PRESTIGE_1_BADGE
    elif reputation_type == "most_wanted":
        if score >= DEMON_MOST_WANTED:
            return DEMON_MOST_WANTED_PRESTIGE_BADGE
        elif score >= MOST_WANTED_LEVEL_3:
            return MOST_WANTED_LEVEL_3_BADGE
        elif score >= MOST_WANTED_LEVEL_2:
            return MOST_WANTED_LEVEL_2_BADGE
        elif score >= MOST_WANTED_LEVEL_1:
            return MOST_WANTED_LEVEL_1_BADGE
    return "UNRANKED"
